buildscript {
    repositories {
        mavenLocal()
        maven { url "https://nexus.ala.org.au/content/groups/public/" }
        maven { url "https://repo.grails.org/grails/core" }
        jcenter()
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
        //classpath "com.bertramlabs.plugins:asset-pipeline-gradle:2.15.1" // remove for upgrade grails 5
        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:3.4.7" // for grails 5
        //classpath 'com.bmuschko:gradle-clover-plugin:2.2.4' // remove for grails 5
    }
}

version "3.1"
group "org.grails.plugins"

apply plugin:"eclipse"
apply plugin:"idea"
apply plugin:"org.grails.grails-plugin"
//apply plugin:"org.grails.grails-plugin-publish"
apply plugin:"asset-pipeline"
apply plugin:"org.grails.grails-gsp"
//apply from: "${project.projectDir}/gradle/clover.gradle"  // remove for grails 5

repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/grails/core" }
    maven { url "https://nexus.ala.org.au/content/groups/public/" }
}

boolean inplace = true

dependencies { // rewritten for grails 5
    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.grails:grails-core"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"
    implementation "org.grails:grails-web-boot"
    implementation "org.grails:grails-logging"
    implementation "org.grails:grails-plugin-rest"
    implementation "org.grails:grails-plugin-databinding"
    implementation "org.grails:grails-plugin-i18n"
    implementation "org.grails:grails-plugin-services"
    implementation "org.grails:grails-plugin-url-mappings"
    implementation "org.grails:grails-plugin-interceptors"
    implementation "org.grails.plugins:cache"
    implementation "org.grails.plugins:async"
    implementation "org.grails.plugins:scaffolding"
    implementation "org.grails.plugins:gsp"
    implementation 'commons-io:commons-io:2.6'
    implementation "org.openclover:clover:4.3.1"
    console "org.grails:grails-console"
    profile "org.grails.profiles:web-plugin"
    compileOnly "org.grails:grails-plugin-services"
    compileOnly "org.grails:grails-plugin-domain-class"
    //compile "com.bertramlabs.plugins:asset-pipeline-grails:2.15.1" // remove for grails 5
    //runtimeOnly "com.bertramlabs.plugins:asset-pipeline-grails:3.4.7" // for grails 5
    implementation "com.bertramlabs.plugins:asset-pipeline-grails:3.4.7" // for grails 5
    implementation "com.bertramlabs.plugins:asset-pipeline-core:3.4.7" // for grails 5

    testImplementation "org.grails:grails-gorm-testing-support"
    //testImplementation "org.grails:grails-plugin-testing" // remove for grails 5
    testImplementation "org.grails:grails-web-testing-support"

    testRuntimeOnly "org.seleniumhq.selenium:selenium-htmlunit-driver:2.47.1"
    testRuntimeOnly "net.sourceforge.htmlunit:htmlunit:2.18"

    testImplementation 'com.codeborne:phantomjsdriver:1.3.0'

    testImplementation "org.grails.plugins:geb"

    testImplementation "org.seleniumhq.selenium:selenium-chrome-driver:$seleniumVersion"
    testRuntimeOnly "org.seleniumhq.selenium:selenium-firefox-driver:$seleniumVersion"
//  testRuntime "org.seleniumhq.selenium:selenium-safari-driver:$seleniumSafariDriverVersion"

    testImplementation "org.seleniumhq.selenium:selenium-remote-driver:$seleniumVersion"
    testImplementation "org.seleniumhq.selenium:selenium-api:$seleniumVersion"
    testImplementation "org.seleniumhq.selenium:selenium-support:$seleniumVersion"

    if (!inplace) {
        implementation ("org.grails.plugins:ala-map-plugin:3.0") {
            exclude group: 'com.bertramlabs.plugins', module: 'asset-pipeline-grails'
        }
    }
}

tasks.withType(Test) {
    systemProperty 'geb.env', System.getProperty('geb.env') ?: 'chromeHeadless'
    systemProperty "geb.build.reportsDir", reporting.file("geb/integrationTest")

    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat 'full'
    }
}

bootRun {
    jvmArgs('-Dspring.output.ansi.enabled=always')
    // addResources = true // remove for grails 5
    String springProfilesActive = 'spring.profiles.active'
    systemProperty springProfilesActive, System.getProperty(springProfilesActive)
}
// enable if you wish to package this plugin as a standalone application
//bootRepackage.enabled = false // remove for grails 5

assets {
    packagePlugin = true

    excludes = [ // for grails 5 to work
        'regex:.*hintrc.*\\.js'
    ]    
}

/* remove for grials 5
publishing {
    repositories {
        maven {
            name 'Nexus'
            url "https://nexus.ala.org.au/content/repositories/${project.version.endsWith('-SNAPSHOT') ? 'snapshots' : 'releases' }"
            credentials {
                username = System.getenv('TRAVIS_DEPLOY_USERNAME')
                password = System.getenv('TRAVIS_DEPLOY_PASSWORD')
            }
        }
    }
    publications {
        mavenJar(MavenPublication) {
            pom.withXml {
                def pomNode = asNode()
                pomNode.dependencyManagement.replaceNode {}

                // simply remove dependencies without a version
                // version-less dependencies are handled with dependencyManagement
                // see https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/8 for more complete solutions
                pomNode.dependencies.dependency.findAll {
                    it.version.text().isEmpty()
                }.each {
                    it.replaceNode {}
                }
            }
            from components.java

        }
    }
}
*/

if (inplace) {
    grails {
        exploded = true
        plugins {
            implementation (project(':ala-map-plugin'))
        }
    }
}

task _Events {
    doLast {
        println "Running _Events.groovy script"
        println "${project.projectDir}/_Events.groovy"
        new GroovyScriptEngine(["${project.projectDir}"] as String[]).run("_Events.groovy", new Binding(['projectDir': project.projectDir]))
    }
}

// the tasks used here for dependsOn may be incomplete/incorrect
assetCompile.dependsOn(_Events)
compileGroovy.dependsOn(_Events)
bootRun.dependsOn(_Events)
